### ISSUE TITLE
How to compile the OpenSeesPy for windows in VS2019

### ISSUE THREAD

**Issue by kangjianfei** [zhuminjie/OpenSeesPyDoc#167]
I successfully compiled OpenSees in VS2019 for windows following the prompts at https://github.com/OpenSees/OpenSees/issues/209. 
Seeing the convenience of OpenSeespy, I want to compile OpenSeespy for windows in VS2019. Can you give me a guide?

**Comment by ahartloper** [comment]
See below for some instructions that I wrote elsewhere that could help

### Help for building OpenSees

Regardless of your system, ensure that you have TCL installed according to the instructions provided on the OpenSees download page (http://opensees.berkeley.edu/OpenSees/user/download.php).

#### Compiling on Windows

##### Linking fortran compiler

You will require the Intel Fortran compiler for Windows, this comes with the student license of Intel Parallel Studio.
To link with the fortran compiler:
1. Right click on the OpenSees project in the **Solution Explorer** and select **Properties**
1. Make sure that in the Configuration bar **"All Configurations"** is selected
1. Expand **Linker** under **Configuration Properties** and select **General** under Linker
1. Click on **Additional Library Directories** in the main box and edit this entry
1. Add another directory that includes the library files for intel fortran (e.g,. `C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2019\windows\compiler\lib\intel64_win`)
1. Accept the change by clicking OK etc.

Note that the location of the folder will change depending on your version of Intel parallel studio and where you installed it.
You could probably use gfortran instead of Intel fortran, but I don't go into that here.

##### Building OpenSees (TCL)

1. Link the fortran compiler
1. Choose the build configuration (either Debug or Release)
1. Right click on the **OpenSees** project in the **Solution Explorer** and select **Build**

If there are no errors an OpenSees.exe will be created in `OpenSees/Win64/bin/`.


##### Building OpenSeesPy36

Ensure you have installed a Python distribution, I recommend Anaconda Python3.
You will need to link some Python libraries and header files, to locate these directories open a terminal and enter `python` to open the Python prompt.
In the prompt, enter
```Python
# thanks to https://stackoverflow.com/a/35071359
from sysconfig import get_paths
from pprint import pprint

info = get_paths()  # a dictionary of key-paths

# pretty print it for now
pprint(info)
```
For me the output is
```Python
{'data': 'C:\\Users\\hartlope\\AppData\\Local\\Continuum\\Anaconda3',
 'include': 'C:\\Users\\hartlope\\AppData\\Local\\Continuum\\Anaconda3\\Include',
 'platinclude': 'C:\\Users\\hartlope\\AppData\\Local\\Continuum\\Anaconda3\\Include',
 'platlib': 'C:\\Users\\hartlope\\AppData\\Local\\Continuum\\Anaconda3\\Lib\\site-packages',
 'platstdlib': 'C:\\Users\\hartlope\\AppData\\Local\\Continuum\\Anaconda3\\Lib',
 'purelib': 'C:\\Users\\hartlope\\AppData\\Local\\Continuum\\Anaconda3\\Lib\\site-packages',
 'scripts': 'C:\\Users\\hartlope\\AppData\\Local\\Continuum\\Anaconda3\\Scripts',
 'stdlib': 'C:\\Users\\hartlope\\AppData\\Local\\Continuum\\Anaconda3\\Lib'}
```
I will call e.g., `C:\\Users\\hartlope\\AppData\\Local\\Continuum\\Anaconda3` as `<python_path>`

Now we are ready to build the OpenSeesPy36 project:
1. Follow the instructions for linking the fortran compiler, but select the OpenSeesPy36 project instead.
1. Add another entry to the **Additional Library Directories** (similar to the fotran compiler directory): `<python_path>\libs`
1. **Under Configuration Properties**, select **VC++ Directories**
1. Add an additional entry to **Include Directories**: `<python_path>\Include`
1. Accept the changes
1. Choose the build configuration (either Debug or Release)
1. Right click on the **OpenSeesPy36** project in the **Solution Explorer** and select **Build**

If there are no errors an opensees.pyd will be created in `OpenSees/Win64/bin/py36/`.

**Comment by kangjianfei** [comment]
Dear ahartloper
Thank you for your answer. I tried it. Although there still be an error message, it may be the problem of the C language header file reference. I will continue to try.

**Comment by ahartloper** [comment]
What's the error?

**Comment by kangjianfei** [comment]
![1](https://user-images.githubusercontent.com/48382725/79217803-043a4f80-7e82-11ea-9862-ac13a8ccb23d.png)
The source code I try to compile is ‘OpenSees Version 3.2.0’ （https://github.com/OpenSees/OpenSees/releases）and Python 3.6.8

**Comment by ahartloper** [comment]
1) Can you build the "standard" OpenSees project that uses the TCL interpreter? One thing I noticed now is that you have to build the OpenSees project then the OpenSeesPy36 project.

2) Are these the first few errors that you show? It looks like `PythonModule` does not compile, which causes the rest of the errors.

**Comment by kangjianfei** [comment]
Dear ahartloper
I found the problem! When using the Pyenv to manage python version, I downloaded the 32-bit python 3.6.8 by mistake. I modified it to 64-bit, and the compilation was successful. Thank you very much for your help!

**Comment by ahartloper** [comment]
@kangjianfei Good to know!
