### ISSUE TITLE
ZeroLengthSection Element errors

### ISSUE THREAD

**Issue by amihirata** [zhuminjie/OpenSeesPyDoc#43]
Dr. Zhu,
I was attempting to implement the ZeroLengthSection element into a code, however I was unable to get it to work.   I have written a simple code which attempts to implement it in a lateral load analysis, however I get the error that the “-factorization failed, matrix singular U(i,i) = 0, i= 7”

Additionally, on the openseespy website the command structure is as follows:
element('zeroLengthSection', eleTag, *eleNodes, secTag[, '-orient', *vecx, *vecyp][, '-doRayleigh', rFlag])
however I think some of the commas are misplaced and it should be:
element('zeroLengthSection', eleTag, *eleNodes, secTag, [ '-orient', *vecx, *vecyp], [ '-doRayleigh', rFlag])
where the commas are outside the brackets.  (similarly for elasticbeamcolumn and other element types)

Thank you,
Amedeo Hirata 

[ZLS test.zip](https://github.com/zhuminjie/OpenSeesPyDoc/files/2797144/ZLS.test.zip)

**Comment by zhuminjie** [comment]
The reason is that the fiberSection contains only force-deformation response of "P" and "Mz", which corresponds to local x and rotational direction. The local y direction is not connected and that causes singular stiffness matrix. You need a section('Aggregator',...) to add the local y direction on top of the fiber section, something like

mats = [matTag, 'Vy']
section('Aggregator',secTag,*mats,'-section',fiberSecTag)

element('zeroLengthSection', eleTag, *eleNodes, secTag)
