### ISSUE TITLE
stressStrain recorder help

### ISSUE THREAD

**Issue by vacalderon** [zhuminjie/OpenSeesPyDoc#84]
Hello I am trying to obtain the stressStrain for a given point in a section using openseespy forceBeamColumn, I am imputing:

recorder('Element', '-file', datadir + '/StressStrain.out', '-time','-ele', 1, 'section', 1, 'fiber', 9.768946, 0, 'mat',3,'stressStrain')

After fiber is the position where I want to obtain the stress strain relationship for a circular concrete column I am specifying material 3 which is a steel since at that position I have a reinforcing bar, my output only shows the time series if I specify this, it shows stress strain for all integration section if I input:

recorder('Element', '-file', datadir + '/StressStrain2.out', '-time','-ele', 1, 'section', 1, 'fiber', '1', 'stressStrain')

But I don't have control on the point where I am obtaining the stress strain relationship. Could you clarify how to input the stressStrain recorder using openseespy.

**Comment by vacalderon** [comment]
I figured my mistake, thank you I wasn't inputing the section tag as string.

**Comment by zhuminjie** [comment]
Thank you for your comments

**Comment by randomcrit2020** [comment]
> I figured my mistake, thank you I wasn't inputing the section tag as string.

how did you do it?

**Comment by 2020CES2736** [comment]
I am also having same problem. I am getting single row of pseudo time steps in the output file for stress strain that I wanted to generate for a core concrete fiber inside a fiber section. I tried to input section tag and other tags and coordinates following it  as string by writing them inside " ", ' ', and also str( ).I tried every possible combination that I could think of. None of them work. Can you tell me which version of openseespy are you using? I am using the latest one 3.3.0.0. Please clarify this issue and how did you solve it.

**Comment by zakidotai** [comment]
> I am also having same problem. I am getting single row of pseudo time steps in the output file for stress strain that I wanted to generate for a core concrete fiber inside a fiber section. I tried to input section tag and other tags and coordinates following it as string by writing them inside " ", ' ', and also str( ).I tried every possible combination that I could think of. None of them work. Can you tell me which version of openseespy are you using? I am using the latest one 3.3.0.0. Please clarify this issue and how did you solve it.

I hope this helps: https://portwooddigital.com/2020/08/14/recorders-not-recording/

**Comment by 2020CES2736** [comment]
> > I am also having same problem. I am getting single row of pseudo time steps in the output file for stress strain that I wanted to generate for a core concrete fiber inside a fiber section. I tried to input section tag and other tags and coordinates following it as string by writing them inside " ", ' ', and also str( ).I tried every possible combination that I could think of. None of them work. Can you tell me which version of openseespy are you using? I am using the latest one 3.3.0.0. Please clarify this issue and how did you solve it.
> 
> I hope this helps: https://portwooddigital.com/2020/08/14/recorders-not-recording/

Thank you. I actually found out the issue is with openseespy version 3.3.0.0. It neither takes the tags as integers nor as strings. I downgraded the openseespy version to 3.2.2.9 and input the tags and coordinates  after 'section' as strings and it worked! Hope the developers fix that issue in the upcoming release of openseespy version.

**Comment by mhscott** [comment]
The issue should be fixed in the next release and you won't need to put everything in '' or str(). Sorry about that!

--
Michael H. Scott, Ph.D.
Professor, Structural Engineering
Oregon State University
cce.oregonstate.edu/scott<https://exmail.oregonstate.edu/owa/redir.aspx?C=_F2i-PfJ4o6PTa3_ZQo4PE-QjaGSDCPQO_2ZTY0wP-CV6RK6qknXCA..&URL=https%3a%2f%2fcce.oregonstate.edu%2fscott>
o: 1-541-737-6996
OpenSees blog: www.portwooddigital.com<https://outlook.office.com/mail/options/mail/messageContent/www.portwooddigital.com>
________________________________
